services:
  frontend:
   build: front
   container_name: frontend
   working_dir: /app
   volumes:
     - ./front:/app
   ports:
      - "3000:3000"
   tty: true
  backend:
    build:
      context: ./backend
      dockerfile: build/dockerfile.dev  # 開発用Dockerfile
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    tty: true

  # MySQLデータベース
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: flowgrid
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
  go_cache:

networks:
  default:
    name: flowgrid_network