name = "flowgrid-api"
compatibility_date = "2024-01-01"
main = "./dist/worker"

[env.production]
d1_databases = [
  { binding = "DB", database_name = "flowgrid-db", database_id = "your-database-id-here" }
]

[env.development]
d1_databases = [
  { binding = "DB", database_name = "flowgrid-db-dev", database_id = "your-dev-database-id-here" }
]

[vars]
JWT_SECRET = "your-jwt-secret-key-here"

[build]
command = "go build -o dist/worker ./worker_adapter.go"
