name = "flowgrid"
compatibility_date = "2024-01-01"
main = "./wasm-loader.js"

[build]
command = "docker run --rm -v $(pwd):/app -w /app golang:1.24.6 go build -o dist/worker.wasm workers_main.go"
watch_dir = "."

[env.production]
main = "./wasm-loader.js"

[env.development]
main = "./wasm-loader.js"
