name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # ソースコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v2

      # Goのセットアップ
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24  # 使用しているGoのバージョンを指定

      # golangci-lintのインストール
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh
          sudo mv ./bin/golangci-lint /usr/local/bin

      # インストールが成功したことを確認（バージョン確認）
      - name: Verify golangci-lint installation
        run: golangci-lint --version

      # golangci-lintの実行
      - name: Run golangci-lint
        run: golangci-lint
