name: Deploy Backend to Cloudflare Workers

on:
  push:
    branches: [ main, feature/55 ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

env:
  NODE_VERSION: '20'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.6'
        
    - name: Build Go worker
      run: |
        cd backend
        go mod tidy
        go build -o dist/worker worker_adapter.go
        ls -la dist/
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install Wrangler
      run: npm install -g wrangler
      
    - name: Configure Wrangler
      run: |
        cd backend
        # wrangler.tomlの設定を確認
        cat wrangler.toml
        
    - name: Deploy to Cloudflare Workers
      run: |
        cd backend
        # 事前にビルドしたファイルを直接指定してデプロイ
        WRANGLER_SEND_METRICS=false wrangler deploy --env production dist/worker
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        
    - name: Verify deployment
      run: |
        echo "Deployment completed successfully!"
        echo "Backend API should be available at: https://flowgrid.sintaro-katuta.workers.dev"
